sudo: required
services: docker
language: python
python:
  - "3.6" # Placeholder only
install:
  - pip install codecov
before_script:
  - docker build -t python -f .docker/Dockerfile_python .
  - docker build -t uncertainpy -f .docker/Dockerfile_uncertainpy .
  - ci_env=`bash <(curl -s https://codecov.io/env)`
script:
  - docker run $ci_env -t uncertainpy uncertainpy/run_tests.sh
# before_deploy:
#   - sudo rm -rf src/uncertainpy.egg-info
deploy:
  provider: pypi
  user: simetenn
  skip_cleanup: true
  password:
    secure: Fjr/QrjgahFHGVmttpRDMwiGnHUAxGdNLzcR27JGn4ayHAbN3KXakoVY2iJ3mxIt/TE4GEL/s6709xziJGlEdCzoiXChOevqX/YGlZU/gmg1rDl59MTq7tjiVK3SPiBYC++PmkAlZUs7RxeDRIyyccHaKntlRp7/r57eEffdpw5QQmNHzrm4tcXsI4AlBznhn3bZ4ooQXHsmO6cF9q0l+nUteXn0K1pjPJhw/HRGiTAXcHk97oXVg/L9BheFyWybXwcEDairw2DaFd7YeNJDK1TwXiyNWm89Q4b9z/e2zznxW0tkOSX4cTXha+7aQD3JVvUa3AWLyIEx/6iWz0fw1L4Me9navsMFq5ApTVabP6XbVW8vSPmteBO4JdiDLgWAjjoG1a5iC3dR5ltJEH0VW1N7ENaGTt4CW9MvxZqAjnEwcDPdVpk1a5kw/nBeU3lV8rMv4uGIOgEOiTGSQeu/ISEBSNUuZclHBMOj6HrWx5NJGsvPH8Ktn1XyVACzUt3tDaoN1bSRZbwl1ku4Hxsof9Yoo2WCP2txzzoKgdgGUBw6Z9ZzWa8SrMr5OVsLpsoI3gMISgyYDb8lDRqsiu7v/u1EX6L/Tflea3E80/q8svgqgCei37SxdIIcVn30S1VsJ2sIJu6iKez+GLqTAMTyESNWWFdWTGhZGfLmsn0kIeE=
  on:
    python: 3.6
    tags: true
    distributions: sdist bdist_wheel
    repo: simetenn/uncertainpy
